### ISSUE TITLE
Large bib-file breaks stuff

### ISSUE THREAD

**Issue by chepec** [inukshuk/jekyll-scholar#140]
I'm running jekyll/scholar 4.3.3 on Jekyll 2.5.3 (Ruby 2.3.0) , so it may be that this issue has been solved in Jekyll 3, jekyll-scholar 5.x or later Ruby versions. I'm not sure which causes the problem. Unfortunately I'm a little stuck at Jekyll 2 because I need jekyll-pandoc, which doesn't support Jekyll 3 yet.

I have a large bib-file (more than 3000 references, almost 4MB) that throws me the following error when I build the site:

```
Liquid Exception: File name too long @ rb_sysopen -
```
immediately followed by the entire contents of the bib-file printed to the terminal.

Have I hit some limit in size after which Jekyll scholar can't process the bib-file? Is this something anyone is familiar with?

The bib-file is not hand-curated, but generated by Mendeley, so I tested adding `use_raw_bibtex_entry: true` to my `_config.yml` and disabling Mendeley's escaping of LaTeX control characters, but none (neither separetely or in combination) had any effect on the jekyll build error.

I tested removing all but a few references from the bib-file, and then jekyll build works fine and the site looks as expected too. This suggests it is the length of the bib-file that causes the issue.

These are my jekyll-scholar settings in `_config.yml`

```
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: /my-jekyll-site/_bibliography
  bibliography: library.bib
  bibliography_template: "{{reference}}"
  query: "@*"
```
The error message thrown by Jekyll is rather uniformative, so I would also appreciate pointers on how to enable and/or access more detailed jekyll logs?

It would just be awesome and incredibly time-saving if I didn't have to curate a small selection of references in a separate bib-file for each jekyll blog post :-)
