### ISSUE TITLE
Liquid syntax error: Unknown tag 'cite'

### ISSUE THREAD

**Issue by balazsdukai** [inukshuk/jekyll-scholar#162]
I've set up the Jekyll-Scholar plugin by following the instruction in the README and as a result in my `Gemfile` I have:

```
# If you have any plugins, put them here!
gem "jekyll-scholar"
```

furthermore in the `_config.yml` I put:

```
# Load plugins
gems: ['jekyll/scholar']

scholar:
  style: elsevier-with-titles-alphabetical
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: report.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
```

After these steps I ran `bundle install` to install the plugin.

Then I have citations in my document in the format of e.g. `{% cite heijer2012campus %}`. However, when I run `bundle exec jekyll serve` I get the error message `Liquid Exception: Liquid syntax error (line 22): Unknown tag 'cite' in index.md`, where line 22 is simply the first occurrence of a citation with the `cite` tag.

As I am using Ruby and Jekyll the first time, I am not sure if this is an issue or I've just missed something in the configuration files.
