### ISSUE TITLE
Bibliography local override behaviour

### ISSUE THREAD

**Issue by paulvickers** [inukshuk/jekyll-scholar#215]
My config.yml frontmatter has the following settings:

````
scholar:
  style: apa-nvv.csl
  sort_by: year,month
  order: descending
  type_order: [misc,techreport, thesis, book, inbook, proceedings, inproceedings,  article]
   group_by: year,type
  group_order: descending

...  
  bibliography_list_tag: ol
````

Thus I get a numbered list by default. This is for my main publications page. But I have mini bibliographies on individual project pages in which I want bullet lists with no grouping rather than numbered lists. Hence, in each of those pages I have the following override:
````
{% bibliography --cited --group_by none --bibliography_list_tag ul %}
````
Why does it still produce a numbered (ol) list?
