### ISSUE TITLE
repository config option ignored?

### ISSUE THREAD

**Issue by pazz** [inukshuk/jekyll-scholar#324]
Hi there!

I'm trying to use the repository option to enrich the entries with automatically generated links to pdf files but these values are left unset.

1. I'm using the https://github.com/alshedivat/al-folio theme.
2. I placed a directory with some pdfs whose name matches the keys in the bibtex file I'm generating from.
3. I set the config option to the name of that directory (see below for my config)
4. The template (`_layouts/bib.html`) includes `{{ entry.links}}` for debugging purposes.

What I see is that the value of entry.links is unset, renders as empty string.

Are there any restrictions on where the repository dir can be placed, or file permissions or the like?
Any pointers would be much appreciated!
P

---

```yaml
scholar:
  last_name: Totzke
  first_name: ["Patrick",]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details  

  query: "@*"
  repository: bibrepo
```
