### ISSUE TITLE
Help adding a download link to references

### ISSUE THREAD

**Issue by ScribbleGhost** [inukshuk/jekyll-scholar#365]
I have a very hard time displaying files along references. 

What I have checked:
- [x] I have a folder within my site called `downloads` with the file `openai2023gpt.pdf` inside:

```
my-jekyll-site/
├── _bibliography/
│   ├── references.bib
│   └── downloads/
│       └── openai2023gpt.pdf
```

- [x] My post contains: `{% bibliography --file references %}`

- [x] I am using the configuration option`repository: downloads`:
```yml
scholar:
  style: apa  # or your preferred style
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  repository: downloads
```

- [x] I am not using a custom template.

- [x] In `_bibliography/references.bib` I have:
```bib
@misc{openai2023gpt,
  author       = {OpenAI},
  title        = {GPT-4 Technical Report},
  year         = {2023},
  howpublished = {\url{https://openai.com/research/gpt-4}},
  note         = {Accessed: 2025-05-15}
}
```

The readme says:

> When generating bibliographies, Jekyll-Scholar will look in that folder to see if it contains a filename matching each entry's BibTeX key: if it does, the path to that file will be exposed to the bibliography template as the `link` property.

Do I need a custom HTML template to make this work, or is this feature supposed to work out-of-the-box?

I have been on this issue for some hours. Please advise.
