### ISSUE TITLE
conflicit with  jekyll_figure plugin 

### ISSUE THREAD

**Issue by jiyeqian** [inukshuk/jekyll-scholar#63]
When I use both [jekyll_figure](https://github.com/lmullen/jekyll_figure) and jekyll-scholar, it will show error:

``` bash
 Liquid Exception: Unknown tag 'figure' in _posts/...
```

My _config.yml including:

``` yml
gems: [jekyll/scholar] 
gems: [jekyll_figure]

figures:
  dir: /assets/images
  enumerate: true

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  # source: ./_bibliography
  source: /assets/bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
```
